name: kanban-board-testing

networks:
  default-network:
    driver: bridge

services:
  db:
    image: mysql:8.4.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - default-network
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  all_services_ready:
    image: alpine:3.23.2
    command: tail -f /dev/null
    networks:
        - default-network
    depends_on:
      db:
        condition: service_healthy
